# Generated by Django 4.2 on 2025-03-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_customuser_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hall_ticket_number',
        ),
        migrations.AlterField(
            model_name='student',
            name='hall_ticket_number',
            field=models.CharField(blank=True, default=' ', max_length=15, unique=True),
        ),
    ]
