# Generated by Django 4.2 on 2025-03-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_customuser_hall_ticket_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hall_ticket_number',
            field=models.CharField(blank=True, default=' ', max_length=15),
        ),
    ]
